version: 0.2
            
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - mv target/test-1.0.3-SNAPSHOT.jar ../.

artifacts:
  files:
    - test-1.0.3-SNAPSHOT.jar
